FROM node:7.10.0-alpine

RUN mkdir -p /usr/src/homebrew-monitor-rest
WORKDIR /usr/src/homebrew-monitor-rest

# Install app dependencies
COPY . /usr/src/homebrew-monitor-rest
RUN npm install --production

# run
CMD ["npm", "run", "start"]