version: 2
jobs:
  build:
    only:
      - master
      - publish
    working_directory: /app/homebrew-monitor-rest
    docker:
      - image: node:7.10.0
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Docker
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build Test Image
          command: docker build -t codemeister/homebrew-monitor-rest-test -f ./Dockerfile.test .
      - run:
          name: Run Test Image
          command: docker run -it codemeister/homebrew-monitor-rest-test
      - run:
          name: Log into Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "publish" ]; then
              docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            fi
      - run:
          name: Build Production Image
          command: |
            if [ "${CIRCLE_BRANCH}" == "publish" ]; then
              docker build -t codemeister/homebrew-monitor-rest -f ./Dockerfile.production .
            fi
      - run:
          name: Publish Production Image
          command: |
            if [ "${CIRCLE_BRANCH}" == "publish" ]; then
              docker push codemeister/homebrew-monitor-rest
            fi
      