version: 2
jobs:
  build:
    branches:
      only:
        - master
        - publish
    working_directory: /app/homebrew-monitor
    docker:
      - image: node:7.10.0
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Docker
          command: |
            set -x
            VER="17.04.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build Test Image
          command: docker build -t "${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}-test" -f ./Dockerfile.test .
      - run:
          name: Run Test Image
          command: docker run -it "${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}-test"
      - run:
          name: Install JQ
          command: |
              wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/bin/jq;
              chmod 755 /usr/bin/jq;
      - run:
          name: Log into Docker Hub
          command: |
            currentVersion="$(echo "$(cat package.json)" | jq -jr ".version")"
            exists="$(echo "$(curl -s "https://registry.hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tags/")" | jq -jr ".results[].name == \"${currentVersion}\"" | grep -c "true")" || true
            echo "branch=${CIRCLE_BRANCH} version=${currentVersion} exists=${exists}"
            if [ "${CIRCLE_BRANCH}" == "publish" ] && [ "$exists" == "0" ]; then
              docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            else
              echo "Skipped"
            fi
      - run:
          name: Build Production Image
          command: |
            currentVersion="$(echo "$(cat package.json)" | jq -jr ".version")"
            exists="$(echo "$(curl -s "https://registry.hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tags/")" | jq -jr ".results[].name == \"${currentVersion}\"" | grep -c "true")" || true
            echo "branch=${CIRCLE_BRANCH} version=${currentVersion} exists=${exists}"
            if [ "${CIRCLE_BRANCH}" == "publish" ] && [ "$exists" == "0" ]; then
              docker build -t "${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${currentVersion}" -f ./Dockerfile.production .
            else
              echo "Skipped"
            fi
      - deploy:
          name: Publish Production Image
          command: |
            currentVersion="$(echo "$(cat package.json)" | jq -jr ".version")"
            exists="$(echo "$(curl -s "https://registry.hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tags/")" | jq -jr ".results[].name == \"${currentVersion}\"" | grep -c "true")" || true
            echo "branch=${CIRCLE_BRANCH} version=${currentVersion} exists=${exists}"
            if [ "${CIRCLE_BRANCH}" == "publish" ] && [ "$exists" == "0" ]; then
              docker push "${DOCKER_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${currentVersion}"
            else
              echo "Skipped"
            fi
      
